<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <title>Críticos do Sofá</title>
    <link rel="stylesheet" href="App/Assets/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="App/Assets/css/estilo.css"/>
    <script type="text/javascript" src="App/Assets/js/jquery-1.12.0.min.js"></script>
    <script type="text/javascript" src="App/Assets/js/bootstrap.min.js"></script>
    <!-- Add to homescreen for Chrome on Android -->
</head>
<body>
    <?php echo $this->content();?>
</body>
</html>